package lib;

import java.util.List;

/**
 * {@code DashboardMessage}s are generated by the {@link Dashboard} actor as
 * a result of messages received from the custom dashboard. Each encapsulates
 * a {@linkplain #getType() message type} and {@linkplain #getArgs() list
 * of arguments}.
 *
 * @author Quinn Tucker
 */
public class DashboardMessage implements Message {
	
	private String type;
	private List<String> args;
	
	/** Creates a {@code DashboardMessage} with the given type and arguments. */
	DashboardMessage(String type, List<String> args) {
		this.type = type;
		this.args = args;
	}
	
	/** Returns the type of message sent from the dashboard. */
	public String getType() { return type; }
	
	/** Returns the list of arguments sent from the dashboard. */
	public List<String> getArgs() { return args; }
	
	@Override
	public String toString() {
		return "Message: DashboardMessage";
	}
	
}
